--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/SHOP
build-by-default: true
branches:
- master
projects:
  SHOP:
    path: ""
libs:
- src: jojoe77777/FormAPI/libFormAPI
version: ^2.1.1
...
