name: SHOP
author: NurAzliYT
main: NurAzliYT\SHOP\Main
api: 5.0.0
version: 1.0.0

commands:
 shop:
  description: "Shop Command"
  permission: shop.cmd
  
permissions:
 shop.cmd:
  default: true
